# Generated by Django 3.1.2 on 2020-10-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='post_def.jpeg', upload_to='post_pics'),
        ),
    ]
